version: "3.8"

services:
  backend:
    image: dockerhub
    environment:
      DB_HOST: db
      DB_PORT: 3306
    ports:
      - 3031:3031
    networks:
      - notes
  frontend:
    image: dockerhub
    environment:
      REACT_APP_API_BASE_URL: http://localhost:3031
    ports:
      - 3000:3000
    networks:
      - notes
  db:
    image: mariadb:11.2.2
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3032:3306
    networks:
      - notes
    volumes:
      - ./db:/var/lib/mysql

  networks:
    notes: {}