apiVersion: apps/v1
kind: Deployment

metadata:
  name: notes-be
  namespace: prgms-notes
spec:
  replicas: 1
  selector:
    matchLabels:
      run: notes-be
  template:
    metadata:
      labels:
        run: notes-be
    spec:
      containers:
        - name: notes-backend
          image: ghcr.io/prgms-be-devcourse/notes-be:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: notes-be-config

apiVersion: v1
kind: Service

metadata:
  name: notes-be
  labels:
    run: notes-be
  namespace: prgms-notes
spec:
  type: NodePort
  selector:
    run: notes-be
  ports:
  -port: 3031
    targetPort: 3031
    nodePort: 30031